server:
    port: 8980
spring:
    datasource:
        url: jdbc:mysql://wangdongxu.top:13306/springstudy/useUnicode=true&characterEncoding=utf8&useSSL=false
        username: root
        password: 123456
    security:
        user:
            name: wangdongxu
            password: 142857